import { GridColDef, GridRenderCellParams } from "@mui/x-data-grid";

export const columns: GridColDef[] = [
  {
    field: "pdb_id",
    headerName: "PDB ID",
    hideable: false,
    flex: 0.6,
    headerAlign: "center",
    align: "center",
    minWidth: 120,
  },
  {
    field: "protein1",
    headerName: "Protein 1",
    hideable: false,
    flex: 1.5,
    headerAlign: "center",
    align: "center",
    minWidth: 200,
  },
  {
    field: "protein2",
    headerName: "Protein 2",
    hideable: false,
    flex: 1.5,
    headerAlign: "center",
    align: "center",
    minWidth: 200,
  },
  {
    field: "mutations",
    headerName: "Mutation(s)",
    hideable: false,
    headerAlign: "center",
    align: "center",
    flex: 0.7,
    minWidth: 100,
  },
  {
    field: "experiment",
    headerName: "Experiment Technique",
    headerAlign: "center",
    align: "center",
    flex: 1,
    minWidth: 200,
  },
  {
    field: "temperature",
    headerName: "Temperature (K)",
    flex: 0.7,
    headerAlign: "center",
    align: "center",
    minWidth: 150,
  },
  {
    field: "ph",
    headerName: "pH",
    flex: 0.5,
    headerAlign: "center",
    align: "center",
    minWidth: 100,
  },
  {
    field: "delta_g",
    headerName: "ΔG (kcal/mol)",
    flex: 0.7,
    headerAlign: "center",
    align: "center",
    minWidth: 130,
  },
  {
    field: "delta_delta_g",
    headerName: "ΔΔG (kcal/mol)",
    flex: 0.7,
    headerAlign: "center",
    align: "center",
    minWidth: 150,
    renderCell: (params: GridRenderCellParams) =>
      params.value === null ? "-" : params.value,
  },
  {
    field: "pubmed_id",
    headerName: "PubMed ID",
    headerAlign: "center",
    align: "center",
    flex: 0.6,
    minWidth: 150,
  },
  {
    field: "authors",
    headerName: "Author(s)",
    flex: 1,
    headerAlign: "center",
    minWidth: 150,
  },
  {
    field: "journal",
    headerName: "Journal",
    flex: 1,
    headerAlign: "center",
    align: "center",
    minWidth: 200,
    renderCell: (params: GridRenderCellParams) => params.value || "-",
  },
];

export default columns;
