# fly.toml app configuration file generated for pbax-server on 2023-10-03T19:28:33+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pbax-server"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
